<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\pilot.core\pilot.core.csproj" />
    <ProjectReference Include="..\pilot.res\pilot.res.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>..\lib\revit2026\RevitAPI.dll</HintPath>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>..\lib\revit2026\RevitAPIUI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
