<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ImageResources\Cube-Red-16-Dark.tiff" />
    <None Remove="ImageResources\Cube-Red-32-Dark.tiff" />
    <None Remove="ImageResources\hello-16-dark.tiff" />
    <None Remove="ImageResources\hello-16-light.tiff" />
    <None Remove="ImageResources\hello-16.tiff" />
    <None Remove="ImageResources\hello-32-dark.tiff" />
    <None Remove="ImageResources\hello-32-light.tiff" />
    <None Remove="ImageResources\hello-32.tiff" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ImageResources\hello-16-dark.tiff" />
    <EmbeddedResource Include="ImageResources\hello-16-light.tiff" />
    <EmbeddedResource Include="ImageResources\hello-32-dark.tiff" />
    <EmbeddedResource Include="ImageResources\hello-32-light.tiff" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>..\lib\revit2026\RevitAPI.dll</HintPath>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>..\lib\revit2026\RevitAPIUI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
